---
title: Mollusken
author:
  - name: Katja Lassauer
    email: katjalassauer@sunrise.ch
    phone: 041 360 09 32, 076 563 81 61
    affiliations:
      - name: Zürichstrasse 79, 6004 Luzern
# 24.10.2024
---

Autor:In          | Kontakt
------------------|------------------------------------------
Katja Lassauer   | Zürichstrasse 79, 6004 Luzern


: {tbl-colwidths="[50,50]"}




## Methodik

Die Kartierung fand an vier Tagen im Sommer 2024 vom 10. bis 13. Juli statt. Ausgeführt wurden die Arbeiten von Katja Lassauer (Hauptverantwortung) und Christian Rogenmoser.

Die Wetterbedingungen waren für eine Molluskenaufnahme optimal. Es hatte vorgängig oft geregnet, und auch in der Nacht vom 11. auf den 12. und am Abend des 12. Juli gab es erneut Niederschläge, so dass Erdreich und Vegetation entsprechend feucht waren.

Gesucht wurde hauptsächlich auf Sicht in möglichst unterschiedlichen Biotopen. Dabei machte die Suche durch Abklopfen der Vegetation mithilfe eines Frisbees einen grossen Anteil aus. Dies ist eine effektive Methode, um kleine und kleinste Arten, die sich an Gräsern, Seggen und kleinen Sträuchern aufhalten, zu erfassen. Ebenfalls wurden an geeignet erscheinenden Stellen Bodenproben vor Ort entnommen, gesiebt und ausgelesen. An drei Abenden wurden zudem Nachtexkursionen durchgeführt, wobei das Hauptaugenmerk auf der Erfassung der Nacktschneckenfauna lag.

Besammelte Biotope: feuchte und schattige Felswände (11), überwachsene und bemooste Felsbänder (2, 9, 14, 24), Feuchtwiesen (3, 12, 16), Entwässerungsgräben (3, 12, 18), Übergangsmoor (6, 17), Hochmoor (21), Trockenwiesen (20, 27), Gebirgsnadelwald (4, 5, 7, 10, 15, 19, 25), verrottende Holzbeige (7), Feldgehölz (8, 27), Trockenmauern (22, 23, 26, 27), Gemüsegarten (22), Umgebung des Wasserfalls (15), Wegböschungen (1, 4, 13).

Nicht untersucht wurde die Schlucht unterhalb des Wasserfalls. Hier würde sich eine Bearbeitung möglicherweise lohnen, um zusätzliche Arten nachweisen zu können. Allenfalls würde auch die Entnahme von grösseren Bodenproben an geeigneten Stellen eine Ergänzung der Artenliste bringen.

Die Kartierung fand nach den Richtlinien für die Bearbeitung eines Stichprobenquadranten im Rahmen der Roten Liste 2021 - 2025 statt. Es wurden folgende Daten erhoben: Art, Nachweisqualität, Bestimmungsmethode, Suchmethode, Tag, Monat, Jahr, Gemeinde, Kanton, Lokalnamen, geographische Koordinaten, Genauigkeit derselben, Höhe, Lebensraumtypologie gemäss Delarze et al., Name des Beobachters, sowie Name des Bestimmers.

Ein längerfristiges Monitoring, basierend auf den erhobenen Daten, wäre denkbar, um allfällige Biotopveränderungen aufzuzeigen.

Die gesammelten Daten wurden ans CSCF übermittelt, die Belegexemplare werden in die Molluskensammlung des Naturmuseums Luzern aufgenommen.

## Ergebnisse

Insgesamt konnten 23 Taxa nachgewiesen werden. Bei rund einem Drittel der Arten handelt es sich um Nacktschnecken, vierzehn Arten betreffen Gehäuseschnecken. Des Weiteren wurde eine Muschelart aus der Familie der Pisidien gefunden.

Aufgrund der kalkarmen geologischen Beschaffenheit (Glimmerschiefer/ Gneis) des Untergrundes war eine artenarme Molluskenfauna zu erwarten. Es verwundert daher nicht, dass die Anzahl der Nacktschneckenarten verhältnismässig hoch ist, da diese Arten weniger kalkabhängig sind.

### Nachgewiesene Arten

Unter den gefundenen Arten gilt lediglich *Causa holosericea* laut Roter Liste Mollusken Stand 2010 als verletzlich. Die Genabelte Maskenschnecke ist für den gesamten Alpenraum nachgewiesen, kommt im Tessin aber südlich der Magadinoebene nicht vor. Sie lebt vorwiegend in subalpinen Nadelwäldern auf einer Höhe zwischen 1000 und 2200 m, wo sie sich hauptsächlich in Felsspalten und Gesteinsschutt, aber auch in alten spaltenreichen Mauern oder in der Bodenstreu aufhält.

Besonders zahlreich wurde eine typisch südwestalpine Felsbewohnerin, *Chilostoma zonatum*, angetroffen. Obwohl es sich hier mit 18 -- 26 mm Durchmesser um eine grössere Gehäuseschnecke handelt, wird sie oft übersehen, da sie, wie *Causa holosericea,* ein heimliches Leben in Felsspalten, klüftigen Felsen und Schutt führt.

Beeindruckend war die enorme Dichte an *Arion vulgaris* sowohl im Dorf als auch in der Umgebung. Zurückzuführen ist dies möglicherweise auf die jahrzehntelange biologische und somit eher molluskenfreundliche (giftfreie) Bewirtschaftung der Gärten.

Zwischen den zahlreichen Spanischen Wegschnecken fand sich aber immer wieder auch *Limax sarnensis* mitten im Dorf, was sehr überraschend war. Normalerweise ist der Sarner Schnegel als alpine Waldart und nicht als Kulturfolger bekannt. Eigentlich wäre *Limacus flavus* in der Siedlung zu erwarten gewesen, der aber nicht angetroffen wurde.

Während gewisse Arten wie *Euconulus fulvus* und *Nesovitrea petronella* häufig auftraten, wurde *Aegopinella pura* lediglich einmal gefunden. Erfreulich ist auch der Nachweis von *Arianta arbustorum*, die im Tessin generell selten ist und im Südtessin ganz fehlt.

Zu erwähnen ist ausserdem der Fund einer Muschelart aus der Familie der Pisidien, die in grosser Anzahl angetroffen wurde.

### Fehlende Arten

Bemerkenswert ist, dass die Familie der *Clausilidae* (Schliessmundschnecken) gänzlich abwesend zu sein scheint, obwohl es durchaus Arten gibt, die weniger kalkabhängig sind. Hier würde sich eine intensive Nachsuche möglicherweise lohnen.

## Vorschläge Fördermassnahmen

Da Schnecken bekanntlich nicht sehr mobil sind, ist es entsprechend schwierig, sie durch Schaffung geeigneter Lebensräume gezielt zu fördern. Im Falle von Ces ist es primär wichtig, die vorhandene Vielfalt der Biotope zu erhalten. Insbesondere Kleinstrukturen wie Trockenmauern oder Gebüschgruppen, bzw. Einzelbäume im Feld bieten wertvollen Lebensraum in einer eher molluskenfeindlichen Umgebung.



## Anhang

Unter folgendem Link können die Excelliste mit den Daten zu den Funden, die Fotos im Original, sowie ein Video der Paarung von Limax sarnensis abgerufen werden.

<https://www.dropbox.com/scl/fo/kq6n2d5meycnbkw0v20zz/AGS-otcB16-HQGKH2CO_PYI?rlkey=2qchpzsxyoaqlgv5gqrhjgpxp&dl=0>


