---
title: Wildbienen
author:
  - name: Lorenz Achtnich
    email:  achtnichlorenz@gmail.com
    phone:  079 298 49 44
    affiliations:
      - name: naturalisten.ch, General-Guisan-Strasse 37, 8400 Winterthur
# 29.11.2024
---


Autor:In          | Kontakt
------------------|------------------------------------------
Lorenz Achtnich       | naturalisten.ch, General-Guisan-Strasse 37, 8400 Winterthur

: {tbl-colwidths="[50,50]"}


## Methodik

Um möglichst viele der im Untersuchungsgebiet präsenten Wildbienenarten nachweisen zu können, wurden während vier Zeitfenstern, angelehnt an die Methodik der Roten Liste der Bienen (Müller & Praz, 2016), Bienen aufgesammelt. Mit dieser Methodik lässt sich das phänologische Spektrum der Wildbienenarten vom Frühling bis im Spätsommer gut erfassen. Die Begehungen fanden an folgenden Daten statt:

-   10\. und 11. Mai, 15. und 16. Juni, 13. und 14 Juli, 16. und 17. August

Die Begehungen wurden an möglichst wettersicheren Tagen mit sonnigem Wetter (über 15 °C) und windarmen Verhältnissen zwischen 9 und 18 Uhr durchgeführt. Das Untersuchungsgebiet wurde möglichst flächendeckend abgeschritten und dabei ein Fokus auf Nahrungs- und Nistressourcen der Wildbienen gelegt. Die Wildbienen wurden mit einem Kescher gefangen. Bei im Feld sicher bestimmbaren Individuen wurde die Art und das Geschlecht notiert und das Tier anschliessend wieder freigelassen. Nicht sicher bestimmbare Individuen wurden gesammelt, präpariert und später unter dem Binokular bestimmt. Die Artbestimmung wurde, insbesondere bei schwierig bestimmbaren Arten durch den Wildbienenexperten Andreas Müller überprüft. Alle Feldbeobachtungen und gesammelten Tiere wurden punktgenau lokalisiert und nach Möglichkeit wurden zusätzliche Beobachtungen (Blütenbesuch, Nistverhalten o.ä.) vermerkt. Sämtliche Daten wurden dem CSCF / info fauna gemeldet.

## Ergebnisse

Im Untersuchungsgebiet wurden gesamthaft 81 Arten (264 Individuen) nachgewiesen was gut 20 % der 387 im Kanton Tessin nachgewiesenen Wildbienenarten entspricht (CSCF, o. J.). Unter den nachgewiesen Arten befinden sich eine Art der Roten Liste (Müller & Praz, 2024) mit dem Status «verletzlich» (VU) sowie sechs Arten mit dem Status «nahezu bedroht» (NT). Für den Kanton Tessin konnte mit *Hoplitis robusta* ein Erstnachweis erbracht werden. Obwohl auf dem Gemeindegebiet von Faido in den Jahren 2019 und 2020 im Rahmen der Fauna-Kartierung Doro (Rey, 2021) gezielt nach Wildbienen gesucht wurde, sind 41 (50 %) der nachgewiesenen Arten neu für die Gemeinde. Unter den Nachweisen gibt es neben der Art der Roten Liste auch diverse weitere naturschutzrelevante Arten, welche hohe Ansprüche an ihren Lebensraum stellen. Aufgrund ihrer Seltenheit, Gefährdung oder speziellen Anforderungen an ihren Lebensraum sind folgende Arten hervorzuheben (SwissBeeTeam, 2024):

-   *Andrena tarsata*

Die Blutwurz-Sandbiene ist auf der Roten Liste als nahezu bedroht (NT) eingestuft. Der letzte Nachweis dieser Art im Tessin ist über 25 Jahre her. Pollen sammelt sie ausschliesslich auf Rosaceae, insbesondere bei Arten der Gattung *Potentilla*. Auf den extensiven Wiesen und Weiden rund um Ces blühen zur Flugzeit der Art massenhaft *Potentilla*. Zu den Nistplätzen ist wenig bekannt. Die Art legt ihre Nester im Boden wohl an offenen oder spärlich bewachsenen Stellen (z.B. Trampelpfade) an. Dank der kleinräumigen und vielfältigen Bewirtschaftung der Flächen rund um Ces findet die Biene passende Habitatbedingungen.

-   *Bombus gerstaeckeri*

Die Eisenhut-Hummel lebt hauptsächlich in subalpinen Höhenstufe und ist aufgrund ihrer Pollenpräferenz stark an Lebensräume mit grossen Vorkommen ihrer Wirtspflanzen gebunden. Pollen sammelt sie ausschliesslich an Arten der Gattung *Aconitum*. Rund um Ces wurde die Art an den ausgezäunten Beständen von *Aconitum lycoctonum* gefunden.

-   *Hoplitis robusta*

Die Einhorn-Stängelbiene konnte während den Erhebungen in Ces das erste Mal im Kanton Tessin nachgewiesen werden. Es ist eine Art der lichten Wälder und Waldränder (auch Schlagholz- und Windwurfflächen), die möglicherweise von den Auflichtungen im Rahmen der ökologischen Aufwertungen rund um Ces profitiert hat. Die Art sammelt zwar Pollen an verschiedenen Pflanzenfamilen, doch hat sie eine starke Präferenz für *Potentilla*. Die Nester werden in Käferfrassgängen im Totholz angelegt. Besonders wichtig sind daher gut besonnte, lange am Standort bleibende Totholzstrukturen.

-   *Macropis europaea*

Die Auen-Schenkelbiene ist eine Art der Feuchtgebiete. Dem entsprechend wurde die Art um Ces einzig im Flachmoor (Verengo) nachgewiesen. In Art kommt hauptsächlich in Feucht-gebieten vor, weil sie bei der Pollensuche stark auf die Gattung *Lysimachia* spezialisiert ist.

-   *Megachile analis*

Die Birken-Blattschneiderbiene ist eine Art der höheren Lagen und sammelt Pollen lediglich bei zwei Pflanzenfamilien (Campanulaceae und Fabaceae). Rund um Ces konnte die Art insbesondere an *Phyteuma betonicifolium* beobachtet werden. Der deutsche Name zeigt an, dass die Art ihre Brutzellen zur unterirdischen Nestanlage bevorzugt aus Blattstücken von *Betula pendula* baut.

-   *Sphecodes alternatus*

Die Ungewisse Blutbiene ist eine sehr seltene und bedrohte (VU) Kuckucksbienenart. In der Schweiz kommt sie aktuell nur im Kanton Tessin vor und auch hier gibt es nur eine Hand voll Nachweise. Als Kuckucksbiene legt sie ihre Eier in Nester anderer Wildbienen. Welche das sind ist noch nicht abschliessend geklärt.

Die genannten Arten, zusammen mit vielen weiteren erfreulichen Funden wie *Andrena combinata, Andrena fulva, Halictus sexcinctus, Megachile ligniseca, Osmia submicans,* zeigen den grossen ökologischen Wert der Offenflächen und lichten Wälder rund um Ces. Nicht zu vergessen und als Bienenhabitat nicht zu unterschätzen sind die Gemüsegärten und eingezäunten Beerensträucher. Eine Vielzahl von Arten finden hier Nahrungs- und Nistressourcen.

## Vorschläge Fördermassnahmen

Allgemein scheinen die Wildbienen im untersuchten Areal gute Lebensbedingungen vorzufinden. Die umgesetzten Massnahmen zu Offenhaltung, sei es durch Mahd, Beweidung oder Auslichtung der Baumbestände, sind für die Wildbienen förderlich. Das gleich mehrere, auf *Potentilla* sowie *Campanula/Phyteuma* spezialisierte Arten nachgewiesen werden konnten verdeutlicht das grosse Angebot an Pollenressourcen dieser Pflanzengattungen. Diese Pollenquellen (und natürlich alle weiteren) in ihrer Quantität und Kontinuität zu erhalten und zu fördern sollte Ziel bei der Bewirtschaftung sein. Einige weitere gezielte Fördermassnahmen für nachgewiesene Arten:

-   Blühzeitpunkt von wichtigen Pollenquellen bei der Mahd berücksichtigen. Insbesondere *Campanula (scheuchzerii), Phyteuma (betonicifolium), Potentilla (erecta), Cirsium (palustre, heleioides), Aconitum (lycotonum).*

-   Schonen und Stecklingsvermehrung von männlichen *Salix* als Pollenquelle.

-   Schaffen von offenen Bodenstellen an gut besonnten und drainierten Stellen, beispielsweise am Hang unterhalb *In Scétt*.

-   Freistellen von Totholz und Schaffung von neuem stehendem Totholz durch Ringeln, sowie deponieren von liegendem Totholz an sonnenexponierten Plätzen

## Quellen

Zitierte Literatur

CSCF. (o. J.). Verbreitungskarten Tierarten, info fauna---Centre national de données et d'informations sur la faune de Suisse. Abgerufen 21. Oktober 2023, von https://lepus.infofauna.ch/carto

Müller, A., & Praz, C. (2016). *Rote Liste der Wildbienen der Schweiz Unterlagen für Mitarbeitende*. unveröffentlicht.

Müller, & Praz, C. (2024). *Rote Liste der Bienen---Gefährdete Arten der Schweiz.* Bern: Bundesamt für Umwelt (BAFU) und Info Fauna.

Rey, A. (2021). *Faunakartierung 1019 und 2020---Kulturlandschaft und Artenvielfalt in Doro (Chironico, Gemeinde Faido TI). Verein ‚Amici di Doro'*.

SwissBeeTeam. (2024). *Online-Atlas der Schweizerischen Wildbienen. InfoFauna, Neuchâtel, https://species.infofauna.ch/groupe/1*.



## Anhang

Exceltabelle mit allen Rohdaten: Wildbienenerhebung_Ces_2024_Rohdaten.xlsx

- Tab.1: Alle Rohdaten mit Datum, Koordinaten, Art, Geschlecht und evt Angaben an welcher Pflanze gefangen
- Tab. 2: Sichtbeobachtungen, die nicht gefangen wurden
- Tab. 3: Artenliste mit den 81 nachgewiesenen Arten
- Tab. 4: Übersichtstabelle für den Bericht mit RL Status, deutschen Namen, Bemerkung und ob die Art in der Gemeinde Faido schon bekannt war

- Ordner: Fotos zu Bericht: Fotos zu den Artprofilen für den Publikumsbericht
- Ordner Weitere Bilder:  Eine Auswahl an Bildern, welche man vielleicht brauchen könnte


